name: screen_capture
description: "A Flutter plugin for screen recording on macOS and iOS, supporting system audio."
version: 1.0.0
homepage: https://github.com/TheBilalJaved/screen_capture

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterScreenCapturePlugin
      ios:
        pluginClass: FlutterScreenCapturePlugin

  # Uncomment the following lines to add assets to your plugin package.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment the following lines to add custom fonts to your plugin package.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
